SOURCE: GTA
TARGET: BDD
NUM_WORKERS: 4
TRAIN:
  OCDA_METHOD: baseline
  DA_METHOD: AdvEnt
  MODEL: DeepLabv2_VGG
  MULTI_LEVEL: False
  LAMBDA_ADV_MAIN: 0.01 # lsgan
  LAMBDA_ADV_AUX: 0.0002
TEST:
  MODE: best