SOURCE: GTA
TARGET: BDD
NUM_WORKERS: 4
TRAIN:
  OCDA_METHOD: ad_boundary # advanced test version -> ad_boundary
  DA_METHOD: source_only
  MODEL: DeepLabv2_VGG
  LAMBDA_BOUNDARY: 0.5
  BOUNDARY_LOSS: BCE  #  [ "BCE", "DICE", "BCE+DICE" ]
TEST:
  MODE: best
#  MODE: single
#  RESTORE_FROM:
#    - ../../experiments/snapshots/GTA2BDD_DeepLabv2_VGG_source_only_boundary_BCE_twinClassfier/model_42000.pth