SOURCE: GTA
TARGET: BDD
NUM_WORKERS: 4
TRAIN:
  OCDA_METHOD: selfTrain
#  DA_METHOD: source_only
  DA_METHOD: AdapSeg
  MODEL: DeepLabv2_VGG
  SELF_TRAINING: True
#  RESTORE_FROM_SELF: GTA2BDD_DeepLabv2_VGG_source_only_baseline_resize/model_46000.pth # source only 25.74
  RESTORE_FROM_SELF: GTA2BDD_DeepLabv2_VGG_AdapSeg_baseline_lsgan/model_62000.pth # adaptseg 30.11
  SHUFFLE: False
  MULTI_LEVEL: False
  LAMBDA_ADV_MAIN: 0.01
  LAMBDA_ADV_AUX: 0.0002
TEST:
  MODE: best